### ISSUE TITLE
Categoriesare time ?

### ISSUE THREAD

**Issue by adamdab** [PW-MiNI-IO2-2023-Group-3/Specyfikacja#13]
In POST /event we specify categories as integers with description 'Unix time stamp of end of event (required)'. Wut is this ? Can we change it to be categories instead or names ?

**Comment by Xevi8X** [comment]
Copy-paste fault. It's just ids of categories

**Comment by Xevi8X** [comment]
Should be like that;
```yaml
- name: categories
          in: query
          description: Array of id of categories that event belong to.
          required: true
          schema:
            type: array
            items:
              type: integer
```
